---
os: osx
osx_image: xcode10
language: swift
script:
    - set -o pipefail
    - gem install xcpretty
    - xcodebuild clean build -workspace GiphySearch.xcworkspace -scheme "Giphy Search" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "OS=12.0,name=iPhone XR"|xcpretty
