----

os: osx
osx_image: xcode10
language: swift
script:
    - set -o pipefail
    - xcodebuild clean build test -project GiphySearch.xcodeproj\
     -scheme "Giphy Search" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO\
     -sdk iphonesimulator -destination "OS=12.0,name=iPhone XR"
